Algoritmo "tabuada"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Valéria Ferreira
// Data atual  : 02/02/2023
//Crie um programa que receba do usuário um número e apresente a tabuada deste.

Var
i, numero: inteiro

Inicio
      escreva("Qual número da tabuada: ")
      leia(numero)
      
      para i de 1 ate 10 faca
           escreval(numero, " X ",  i, " = ", (numero*i))
      fimpara

Fimalgoritmo