Algoritmo "tabuadaEnquanto"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Valéria Ferreira

//Crie um programa que, imprima a tabuada de um número digitado pelo usuário.

Var
   i, numero : inteiro


Inicio

   escreval("TABUADAS")
   escreval("")

   escreval("Digite um número para ver a tabuada: ")
   leia(numero)
   i <- 1
   enquanto i < 11 faca
      escreval(numero, " x ", i, " = ", (numero*i))
      i <- i + 1
   fimenquanto

Fimalgoritmo